function visaChecker() {

    var country = document.getElementById("visitingCountry");

    //var x = country.value.toLowerCase();

    var countries = {
        //'canada': 'No Visa Required. American Passport',
        //'india': 'Indian Visa Required'
        'afghanistan': ' <strong>visa required?: </strong>Visa required[2][3] <br></br> <strong>allowed to stay:</strong> ',
        'albania': ' <strong>visa required?: </strong>Visa not required[5][6] <br></br> <strong>allowed to stay:</strong> 1 year[7]',
        'algeria': ' <strong>visa required?: </strong>Visa required[8][9] <br></br> <strong>allowed to stay:</strong> ',
        'andorra': ' <strong>visa required?: </strong>Visa not required[10] <br></br> <strong>allowed to stay:</strong> 3 months[11][12]',
        'angola': ' <strong>visa required?: </strong>eVisa[13][14][15] <br></br> <strong>allowed to stay:</strong> 30 days',
        'antigua and barbuda': ' <strong>visa required?: </strong>Visa not required[18][19] <br></br> <strong>allowed to stay:</strong> 6 months[20]',
        'argentina': ' <strong>visa required?: </strong>Visa not required[22] <br></br> <strong>allowed to stay:</strong> 90 days',
        'armenia': ' <strong>visa required?: </strong>Visa not required[23] <br></br> <strong>allowed to stay:</strong> 180 days',
        'australia': ' <strong>visa required?: </strong>Electronic Travel Authority[24] <br></br> <strong>allowed to stay:</strong> 90 days',
        'austria': ' <strong>visa required?: </strong>Visa not required[27][28] <br></br> <strong>allowed to stay:</strong> 90 days',
        'azerbaijan': ' <strong>visa required?: </strong>eVisa / Visa on arrival[32] <br></br> <strong>allowed to stay:</strong> 30 days[33]',
        'bahamas': ' <strong>visa required?: </strong>Visa not required[37][38] <br></br> <strong>allowed to stay:</strong> 8 months',
        'bahrain': ' <strong>visa required?: </strong>eVisa / Visa on arrival[39] <br></br> <strong>allowed to stay:</strong> 14 days[40]',
        'bangladesh': ' <strong>visa required?: </strong>Visa on arrival[42] <br></br> <strong>allowed to stay:</strong> 30 days[43]',
        'barbados': ' <strong>visa required?: </strong>Visa not required[45][46] <br></br> <strong>allowed to stay:</strong> 6 months[47]',
        'belarus': ' <strong>visa required?: </strong>Visa not required[48] <br></br> <strong>allowed to stay:</strong> 30 days',
        'belgium': ' <strong>visa required?: </strong>Visa not required[53] <br></br> <strong>allowed to stay:</strong> 90 days',
        'belize': ' <strong>visa required?: </strong>Visa not required[55][56] <br></br> <strong>allowed to stay:</strong> 180 days[57]',
        'benin': ' <strong>visa required?: </strong>eVisa[59][60] <br></br> <strong>allowed to stay:</strong> 90 days',
        'bhutan': ' <strong>visa required?: </strong>Visa required[62] <br></br> <strong>allowed to stay:</strong> ',
        'bolivia': ' <strong>visa required?: </strong>Visa on arrival[64][65] <br></br> <strong>allowed to stay:</strong> 90 days[66]',
        'bosnia and herzegovina': ' <strong>visa required?: </strong>Visa not required[69][70] <br></br> <strong>allowed to stay:</strong> 90 days',
        'botswana': ' <strong>visa required?: </strong>Visa not required[72][73] <br></br> <strong>allowed to stay:</strong> 90 days',
        'brazil': ' <strong>visa required?: </strong>Visa not required[75][76] <br></br> <strong>allowed to stay:</strong> 90 days',
        'brunei': ' <strong>visa required?: </strong>Visa not required[77][78] <br></br> <strong>allowed to stay:</strong> 90 days',
        'bulgaria': ' <strong>visa required?: </strong>Visa not required[79][80] <br></br> <strong>allowed to stay:</strong> 90 days',
        'burkina faso': ' <strong>visa required?: </strong>Visa on arrival[82] <br></br> <strong>allowed to stay:</strong> 1 month',
        'burundi': ' <strong>visa required?: </strong>Visa required[84] <br></br> <strong>allowed to stay:</strong> ',
        'cambodia': ' <strong>visa required?: </strong>eVisa / Visa on arrival[85] <br></br> <strong>allowed to stay:</strong> 30 days',
        'cameroon': ' <strong>visa required?: </strong>Visa required[88] <br></br> <strong>allowed to stay:</strong> ',
        'canada': ' <strong>visa required?: </strong>Visa not required[90][91] <br></br> <strong>allowed to stay:</strong> 6 months',
        'cape verde': ' <strong>visa required?: </strong>Visa on arrival[94] <br></br> <strong>allowed to stay:</strong> 30 days',
        'central african republic': ' <strong>visa required?: </strong>Visa not required[96][97][98] <br></br> <strong>allowed to stay:</strong> 180 days',
        'chad': ' <strong>visa required?: </strong>Visa required[100][101] <br></br> <strong>allowed to stay:</strong> ',
        'chile': ' <strong>visa required?: </strong>Visa not required[104] <br></br> <strong>allowed to stay:</strong> 90 days[105][106]',
        'china': ' <strong>visa required?: </strong>Visa required[107] <br></br> <strong>allowed to stay:</strong> ',
        'colombia': ' <strong>visa required?: </strong>Visa not required[113][114] <br></br> <strong>allowed to stay:</strong> 90 days',
        'comoros': ' <strong>visa required?: </strong>Visa on arrival[117][118] <br></br> <strong>allowed to stay:</strong> ',
        'democratic republic of the congo': ' <strong>visa required?: </strong>Visa required[119][120] <br></br> <strong>allowed to stay:</strong> ',
        'republic of the congo': ' <strong>visa required?: </strong>Visa required[122][123] <br></br> <strong>allowed to stay:</strong> ',
        'costa rica': ' <strong>visa required?: </strong>Visa not required[125] <br></br> <strong>allowed to stay:</strong> 90 days',
        'côte divoire': ' <strong>visa required?: </strong>eVisa[127] <br></br> <strong>allowed to stay:</strong> 3 months',
        'croatia': ' <strong>visa required?: </strong>Visa not required[129][130] <br></br> <strong>allowed to stay:</strong> 90 days',
        'cuba': ' <strong>visa required?: </strong>Tourist Card required[132] <br></br> <strong>allowed to stay:</strong> 30 days',
        'cyprus': ' <strong>visa required?: </strong>Visa not required[136][137] <br></br> <strong>allowed to stay:</strong> 90 days',
        'czech republic': ' <strong>visa required?: </strong>Visa not required[139][140] <br></br> <strong>allowed to stay:</strong> 90 days',
        'denmark': ' <strong>visa required?: </strong>Visa not required[142][143] <br></br> <strong>allowed to stay:</strong> 90 days',
        'djibouti': ' <strong>visa required?: </strong>eVisa[145] <br></br> <strong>allowed to stay:</strong> 31 days',
        'dominica': ' <strong>visa required?: </strong>Visa not required[146][147] <br></br> <strong>allowed to stay:</strong> 6 months',
        'dominican republic': ' <strong>visa required?: </strong>Visa not required[149][150] <br></br> <strong>allowed to stay:</strong> 30 days',
        'ecuador': ' <strong>visa required?: </strong>Visa not required[151] <br></br> <strong>allowed to stay:</strong> 90 days',
        'egypt': ' <strong>visa required?: </strong>eVisa / Visa on arrival[153] <br></br> <strong>allowed to stay:</strong> 30 days',
        'el salvador': ' <strong>visa required?: </strong>Visa not required[156][157] <br></br> <strong>allowed to stay:</strong> 3 months',
        'equatorial guinea': ' <strong>visa required?: </strong>Visa not required[158] <br></br> <strong>allowed to stay:</strong> 90 days',
        'eritrea': ' <strong>visa required?: </strong>Visa required[160] <br></br> <strong>allowed to stay:</strong> ',
        'estonia': ' <strong>visa required?: </strong>Visa not required[162][163] <br></br> <strong>allowed to stay:</strong> 90 days',
        'eswatini': ' <strong>visa required?: </strong>Visa not required[165] <br></br> <strong>allowed to stay:</strong> 30 days',
        'ethiopia': ' <strong>visa required?: </strong>eVisa / Visa on arrival[167] <br></br> <strong>allowed to stay:</strong> up to 90 days',
        'fiji': ' <strong>visa required?: </strong>Visa not required[170] <br></br> <strong>allowed to stay:</strong> 4 months[171]',
        'finland': ' <strong>visa required?: </strong>Visa not required[172][173] <br></br> <strong>allowed to stay:</strong> 90 days',
        'france': ' <strong>visa required?: </strong>Visa not required[175][176] <br></br> <strong>allowed to stay:</strong> 90 days',
        'gabon': ' <strong>visa required?: </strong>eVisa / Visa on arrival[178] <br></br> <strong>allowed to stay:</strong> 6 months',
        'gambia': ' <strong>visa required?: </strong>Visa required[181][182] <br></br> <strong>allowed to stay:</strong> ',
        'georgia': ' <strong>visa required?: </strong>Visa not required[184] <br></br> <strong>allowed to stay:</strong> 1 year',
        'germany': ' <strong>visa required?: </strong>Visa not required[185] <br></br> <strong>allowed to stay:</strong> 90 days',
        'ghana': ' <strong>visa required?: </strong>Visa required[187][188] <br></br> <strong>allowed to stay:</strong> ',
        'greece': ' <strong>visa required?: </strong>Visa not required[190][191] <br></br> <strong>allowed to stay:</strong> 90 days',
        'grenada': ' <strong>visa required?: </strong>Visa not required[193][194] <br></br> <strong>allowed to stay:</strong> 3 months',
        'guatemala': ' <strong>visa required?: </strong>Visa not required[195] <br></br> <strong>allowed to stay:</strong> 90 days',
        'guinea': ' <strong>visa required?: </strong>Visa required[197] <br></br> <strong>allowed to stay:</strong> ',
        'guinea-bissau': ' <strong>visa required?: </strong>eVisa / Visa on arrival[199] <br></br> <strong>allowed to stay:</strong> 90 days[200]',
        'guyana': ' <strong>visa required?: </strong>Visa not required[202] <br></br> <strong>allowed to stay:</strong> 3 months[203]',
        'haiti': ' <strong>visa required?: </strong>Visa not required[204][205] <br></br> <strong>allowed to stay:</strong> 3 months',
        'honduras': ' <strong>visa required?: </strong>Visa not required[206] <br></br> <strong>allowed to stay:</strong> 3 months',
        'hungary': ' <strong>visa required?: </strong>Visa not required[207][208] <br></br> <strong>allowed to stay:</strong> 90 days',
        'iceland': ' <strong>visa required?: </strong>Visa not required[210][211] <br></br> <strong>allowed to stay:</strong> 90 days',
        'india': ' <strong>visa required?: </strong>eVisa[213] <br></br> <strong>allowed to stay:</strong> 60 days',
        'indonesia': ' <strong>visa required?: </strong>Visa not required[217][218] <br></br> <strong>allowed to stay:</strong> 30 days',
        'iran': ' <strong>visa required?: </strong>Visa required[219] <br></br> <strong>allowed to stay:</strong> ',
        'iraq': ' <strong>visa required?: </strong>Visa required[223] <br></br> <strong>allowed to stay:</strong> ',
        'ireland': ' <strong>visa required?: </strong>Visa not required[226][227] <br></br> <strong>allowed to stay:</strong> 3 months',
        'israel': ' <strong>visa required?: </strong>Visa not required[229] <br></br> <strong>allowed to stay:</strong> 3 months',
        'italy': ' <strong>visa required?: </strong>Visa not required[232][233] <br></br> <strong>allowed to stay:</strong> 90 days',
        'jamaica': ' <strong>visa required?: </strong>Visa not required[235] <br></br> <strong>allowed to stay:</strong> 6 months',
        'japan': ' <strong>visa required?: </strong>Visa not required[237] <br></br> <strong>allowed to stay:</strong> 90 days',
        'jordan': ' <strong>visa required?: </strong>Visa on arrival[239] <br></br> <strong>allowed to stay:</strong> 30 days',
        'kazakhstan': ' <strong>visa required?: </strong>Visa not required[242][243] <br></br> <strong>allowed to stay:</strong> 30 days',
        'kenya': ' <strong>visa required?: </strong>eVisa / Visa on arrival[246] <br></br> <strong>allowed to stay:</strong> 3 months',
        'kiribati': ' <strong>visa required?: </strong>Visa not required[248] <br></br> <strong>allowed to stay:</strong> 30 days',
        'north korea': ' <strong>visa required?: </strong>Travel restricted[250][251][252] <br></br> <strong>allowed to stay:</strong> ',
        'south korea': ' <strong>visa required?: </strong>Visa not required[253] <br></br> <strong>allowed to stay:</strong> 90 days',
        'kuwait': ' <strong>visa required?: </strong>eVisa / Visa on arrival[255] <br></br> <strong>allowed to stay:</strong> 3 months',
        'kyrgyzstan': ' <strong>visa required?: </strong>Visa not required[256] <br></br> <strong>allowed to stay:</strong> 60 days[257]',
        'laos': ' <strong>visa required?: </strong>eVisa / Visa on arrival[258][259] <br></br> <strong>allowed to stay:</strong> 30 days',
        'latvia': ' <strong>visa required?: </strong>Visa not required[261][262] <br></br> <strong>allowed to stay:</strong> 90 days',
        'lebanon': ' <strong>visa required?: </strong>Visa on arrival[264] <br></br> <strong>allowed to stay:</strong> 1 month',
        'lesotho': ' <strong>visa required?: </strong>Visa not required[265] <br></br> <strong>allowed to stay:</strong> 14 days',
        'liberia': ' <strong>visa required?: </strong>Visa required[267] <br></br> <strong>allowed to stay:</strong> ',
        'libya': ' <strong>visa required?: </strong>Visa required[269] <br></br> <strong>allowed to stay:</strong> ',
        'liechtenstein': ' <strong>visa required?: </strong>Visa not required[271] <br></br> <strong>allowed to stay:</strong> 90 days',
        'lithuania': ' <strong>visa required?: </strong>Visa not required[273][274] <br></br> <strong>allowed to stay:</strong> 90 days',
        'luxembourg': ' <strong>visa required?: </strong>Visa not required[276][277] <br></br> <strong>allowed to stay:</strong> 90 days',
        'madagascar': ' <strong>visa required?: </strong>eVisa / Visa on arrival[279] <br></br> <strong>allowed to stay:</strong> 90 days',
        'malawi': ' <strong>visa required?: </strong>Visa on arrival[280] <br></br> <strong>allowed to stay:</strong> ',
        'malaysia': ' <strong>visa required?: </strong>Visa not required[282] <br></br> <strong>allowed to stay:</strong> 3 months',
        'maldives': ' <strong>visa required?: </strong>Free visa on arrival[284][285] <br></br> <strong>allowed to stay:</strong> 30 days',
        'mali': ' <strong>visa required?: </strong>Visa required[286][287] <br></br> <strong>allowed to stay:</strong> ',
        'malta': ' <strong>visa required?: </strong>Visa not required[289][290] <br></br> <strong>allowed to stay:</strong> 90 days',
        'marshall islands': ' <strong>visa required?: </strong>Visa not required[292] <br></br> <strong>allowed to stay:</strong> unlimited',
        'mauritania': ' <strong>visa required?: </strong>Visa on arrival[294] <br></br> <strong>allowed to stay:</strong> ',
        'mauritius': ' <strong>visa required?: </strong>Visa not required[296] <br></br> <strong>allowed to stay:</strong> 90 days[297]',
        'mexico': ' <strong>visa required?: </strong>Visa not required[298][299] <br></br> <strong>allowed to stay:</strong> 180 days',
        'micronesia': ' <strong>visa required?: </strong>Visa not required[302] <br></br> <strong>allowed to stay:</strong> unlimited[303]',
        'moldova': ' <strong>visa required?: </strong>Visa not required[306] <br></br> <strong>allowed to stay:</strong> 90 days',
        'monaco': ' <strong>visa required?: </strong>Visa not required[308] <br></br> <strong>allowed to stay:</strong> 90 days',
        'mongolia': ' <strong>visa required?: </strong>Visa not required[311] <br></br> <strong>allowed to stay:</strong> 90 days',
        'montenegro': ' <strong>visa required?: </strong>Visa not required[313] <br></br> <strong>allowed to stay:</strong> 90 days',
        'morocco': ' <strong>visa required?: </strong>Visa not required[315] <br></br> <strong>allowed to stay:</strong> 3 months[316]',
        'mozambique': ' <strong>visa required?: </strong>Visa on arrival[317] <br></br> <strong>allowed to stay:</strong> 30 days[318]',
        'myanmar': ' <strong>visa required?: </strong>eVisa[319] <br></br> <strong>allowed to stay:</strong> 28 days',
        'namibia': ' <strong>visa required?: </strong>Visa not required[320] <br></br> <strong>allowed to stay:</strong> 3 months[321]',
        'nauru': ' <strong>visa required?: </strong>Visa required[322] <br></br> <strong>allowed to stay:</strong> ',
        'nepal': ' <strong>visa required?: </strong>Visa on arrival[324] <br></br> <strong>allowed to stay:</strong> 90 days',
        'netherlands': ' <strong>visa required?: </strong>Visa not required[326][327] <br></br> <strong>allowed to stay:</strong> 90 days',
        'new zealand': ' <strong>visa required?: </strong>Visa not required[329] <br></br> <strong>allowed to stay:</strong> 90 days[330]',
        'nicaragua': ' <strong>visa required?: </strong>Visa not required[332] <br></br> <strong>allowed to stay:</strong> 90 days',
        'niger': ' <strong>visa required?: </strong>Visa required[334][335] <br></br> <strong>allowed to stay:</strong> ',
        'nigeria': ' <strong>visa required?: </strong>Visa required[337][338] <br></br> <strong>allowed to stay:</strong> ',
        'north macedonia': ' <strong>visa required?: </strong>Visa not required[339] <br></br> <strong>allowed to stay:</strong> 90 days',
        'norway': ' <strong>visa required?: </strong>Visa not required[341][342] <br></br> <strong>allowed to stay:</strong> 90 days',
        'oman': ' <strong>visa required?: </strong>eVisa[344] <br></br> <strong>allowed to stay:</strong> 30 days',
        'pakistan': ' <strong>visa required?: </strong>Online Visa[346] <br></br> <strong>allowed to stay:</strong> ',
        'palau': ' <strong>visa required?: </strong>Visa not required[349] <br></br> <strong>allowed to stay:</strong> 1 year[350]',
        'panama': ' <strong>visa required?: </strong>Visa not required[351] <br></br> <strong>allowed to stay:</strong> 180 days',
        'papua new guinea': ' <strong>visa required?: </strong>eVisa / Visa on arrival[353] <br></br> <strong>allowed to stay:</strong> 60 days',
        'paraguay': ' <strong>visa required?: </strong>Visa on arrival[355] <br></br> <strong>allowed to stay:</strong> 90 days',
        'peru': ' <strong>visa required?: </strong>Visa not required[357] <br></br> <strong>allowed to stay:</strong> 183 days',
        'philippines': ' <strong>visa required?: </strong>Visa not required[359][360] <br></br> <strong>allowed to stay:</strong> 30 days',
        'poland': ' <strong>visa required?: </strong>Visa not required[361] <br></br> <strong>allowed to stay:</strong> 90 days',
        'portugal': ' <strong>visa required?: </strong>Visa not required[363][364][365] <br></br> <strong>allowed to stay:</strong> 90 days',
        'qatar': ' <strong>visa required?: </strong>Visa not required[367] <br></br> <strong>allowed to stay:</strong> 30 days',
        'romania': ' <strong>visa required?: </strong>Visa not required[368][369] <br></br> <strong>allowed to stay:</strong> 90 days',
        'russia': ' <strong>visa required?: </strong>Visa required[371] <br></br> <strong>allowed to stay:</strong> ',
        'rwanda': ' <strong>visa required?: </strong>eVisa / Visa on arrival[375][376] <br></br> <strong>allowed to stay:</strong> 30 days',
        'saint kitts and nevis': ' <strong>visa required?: </strong>Visa not required[378][379] <br></br> <strong>allowed to stay:</strong> 3 months',
        'saint lucia': ' <strong>visa required?: </strong>Visa not required[380][381] <br></br> <strong>allowed to stay:</strong> 6 weeks',
        'saint vincent and the grenadines': ' <strong>visa required?: </strong>Visa not required[382] <br></br> <strong>allowed to stay:</strong> 1 month[383]',
        'samoa': ' <strong>visa required?: </strong>Free Entry Permit on arrival[384] <br></br> <strong>allowed to stay:</strong> 60 days',
        'san marino': ' <strong>visa required?: </strong>Visa not required[386][387] <br></br> <strong>allowed to stay:</strong> ',
        'são tomé and príncipe': ' <strong>visa required?: </strong>Visa not required[388] <br></br> <strong>allowed to stay:</strong> 15 days',
        'saudi arabia': ' <strong>visa required?: </strong>Visa required[390][391] <br></br> <strong>allowed to stay:</strong> ',
        'senegal': ' <strong>visa required?: </strong>Visa not required[394] <br></br> <strong>allowed to stay:</strong> 90 days',
        'serbia': ' <strong>visa required?: </strong>Visa not required[396] <br></br> <strong>allowed to stay:</strong> 90 days',
        'seychelles': ' <strong>visa required?: </strong>Free Visitors Permit on arrival[398] <br></br> <strong>allowed to stay:</strong> 3 months',
        'sierra leone': ' <strong>visa required?: </strong>Visa required[400] <br></br> <strong>allowed to stay:</strong> ',
        'singapore': ' <strong>visa required?: </strong>Visa not required[402] <br></br> <strong>allowed to stay:</strong> 90 days[403]',
        'slovakia': ' <strong>visa required?: </strong>Visa not required[405][406] <br></br> <strong>allowed to stay:</strong> 90 days',
        'slovenia': ' <strong>visa required?: </strong>Visa not required[408][409] <br></br> <strong>allowed to stay:</strong> 90 days',
        'solomon islands': ' <strong>visa required?: </strong>Free Visitors permit on arrival[411] <br></br> <strong>allowed to stay:</strong> 3 months',
        'somalia': ' <strong>visa required?: </strong>Visa on arrival[413] <br></br> <strong>allowed to stay:</strong> ',
        'south africa': ' <strong>visa required?: </strong>Visa not required[414] <br></br> <strong>allowed to stay:</strong> 90 days',
        'south sudan': ' <strong>visa required?: </strong>Visa required[416][417] <br></br> <strong>allowed to stay:</strong> ',
        'spain': ' <strong>visa required?: </strong>Visa not required[419][420] <br></br> <strong>allowed to stay:</strong> 90 days',
        'sri lanka': ' <strong>visa required?: </strong>eVisa / Visa on arrival[422] <br></br> <strong>allowed to stay:</strong> 30 days[423]',
        'sudan': ' <strong>visa required?: </strong>Visa required[424][425] <br></br> <strong>allowed to stay:</strong> ',
        'suriname': ' <strong>visa required?: </strong>eVisa / Tourist card on arrival[427] <br></br> <strong>allowed to stay:</strong> 90 days',
        'sweden': ' <strong>visa required?: </strong>Visa not required[430][431] <br></br> <strong>allowed to stay:</strong> 90 days',
        'switzerland': ' <strong>visa required?: </strong>Visa not required[433][434] <br></br> <strong>allowed to stay:</strong> 90 days',
        'syria': ' <strong>visa required?: </strong>Visa required[436][437] <br></br> <strong>allowed to stay:</strong> ',
        'tajikistan': ' <strong>visa required?: </strong>eVisa[440][441] <br></br> <strong>allowed to stay:</strong> 45 days',
        'tanzania': ' <strong>visa required?: </strong>eVisa / Visa on arrival[443][444][445] <br></br> <strong>allowed to stay:</strong> 3 months',
        'thailand': ' <strong>visa required?: </strong>Visa not required[447] <br></br> <strong>allowed to stay:</strong> 30 days',
        'timor-leste': ' <strong>visa required?: </strong>Visa on arrival[448] <br></br> <strong>allowed to stay:</strong> 30 days',
        'togo': ' <strong>visa required?: </strong>Visa on arrival[450] <br></br> <strong>allowed to stay:</strong> 7 days[451]',
        'tonga': ' <strong>visa required?: </strong>Free visa on arrival[452][453] <br></br> <strong>allowed to stay:</strong> 31 days',
        'trinidad and tobago': ' <strong>visa required?: </strong>Visa not required[454] <br></br> <strong>allowed to stay:</strong> 90 days[455]',
        'tunisia': ' <strong>visa required?: </strong>Visa not required[456] <br></br> <strong>allowed to stay:</strong> 90 days[457]',
        'turkey': ' <strong>visa required?: </strong>eVisa[458][459] <br></br> <strong>allowed to stay:</strong> 3 months',
        'turkmenistan': ' <strong>visa required?: </strong>Visa required[460] <br></br> <strong>allowed to stay:</strong> ',
        'tuvalu': ' <strong>visa required?: </strong>Visa on arrival[463] <br></br> <strong>allowed to stay:</strong> 1 month',
        'uganda': ' <strong>visa required?: </strong>eVisa / Visa on arrival[465] <br></br> <strong>allowed to stay:</strong> 90 days',
        'ukraine': ' <strong>visa required?: </strong>Visa not required[468] <br></br> <strong>allowed to stay:</strong> 90 days',
        'united arab emirates': ' <strong>visa required?: </strong>Free visa on arrival[470][471] <br></br> <strong>allowed to stay:</strong> 30 days',
        'united kingdom': ' <strong>visa required?: </strong>Visa not required[472][473] <br></br> <strong>allowed to stay:</strong> 6 months[474]',
        'uruguay': ' <strong>visa required?: </strong>Visa not required[475] <br></br> <strong>allowed to stay:</strong> 3 months[476]',
        'uzbekistan': ' <strong>visa required?: </strong>eVisa[477][478] <br></br> <strong>allowed to stay:</strong> 30 days',
        'vanuatu': ' <strong>visa required?: </strong>Visa not required[481] <br></br> <strong>allowed to stay:</strong> 30 days',
        'vatican city': ' <strong>visa required?: </strong>Visa not required[483] <br></br> <strong>allowed to stay:</strong> ',
        'venezuela': ' <strong>visa required?: </strong>Visa required[484] <br></br> <strong>allowed to stay:</strong> ',
        'vietnam': ' <strong>visa required?: </strong>eVisa[484] <br></br> <strong>allowed to stay:</strong> 30 days',
        'yemen': ' <strong>visa required?: </strong>Visa required[488][489] <br></br> <strong>allowed to stay:</strong> ',
        'zambia': ' <strong>visa required?: </strong>eVisa / Visa on arrival[491] <br></br> <strong>allowed to stay:</strong> 90 days',
        'zimbabwe': ' <strong>visa required?: </strong>eVisa / Visa on arrival[494] <br></br> <strong>allowed to stay:</strong> 3 months'

    }


    var item = document.getElementById("answer");

    if (country.value.toLowerCase() in countries) {
        //item.innerHTML = countries[country.value];
        item.innerHTML = countries[country.value.toLowerCase()];

    } else {
        item.innerHTML = "No Data Available. Check spelling or try an alternate country name example: 'United Kingdom' instead of 'England'"
    }


    country.value = ""

}